//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Student_Name { get; set; }
        public string Roll_Number { get; set; }
        public string Course { get; set; }
        public string Batch { get; set; }
        public string Status { get; set; }
    }
}
